### ISSUE TITLE
auth end poit

### ISSUE THREAD

**Issue by digitalhobo** [kashif/pusher-parse#2]
hi, thanks for the pusher parse 

I am wondering do you have an example of what would be in /authorise

for app.post('/authorise', function(req, res) {

**Comment by kashif** [comment]
@digitalhobo i though i did in the readme... its more or less copied from my particular use case... where i send the `user-id` as part of the request to `/authorise` and then I confirm if this user exists and then do the authorisation...

**Comment by digitalhobo** [comment]
okydocky, thanks - think i need to do a little more reading to understand whats going on. 
:0)
