### ISSUE TITLE
Error: Can't set params if there is already a query parameter in the url

### ISSUE THREAD

**Issue by konradholub** [kashif/pusher-parse#3]
Hi,
Thank you for the library.

Unfortunately, I am getting error:
Result: Uncaught Error: Can't set params if there is already a query parameter in the url

I debugged it and commented out: requests.js:39
`params: params,`

I know I lost some functionality because of that but it worked. Please look at it in your spare time.
Thank you again

**Comment by kashif** [comment]
ok cool I will have a look @kohol

**Comment by kashif** [comment]
ok @kohol we do not really lose functionality since Parse's `Parse.Cloud.httpRequest` does not use the proxy or timeout options as far as I can see and the rest of the params we are merging into the url. Can you kindly test this? Thanks!

**Comment by konradholub** [comment]
It's working, thank you!

**Comment by kashif** [comment]
great thanks @kohol actually, would you mind writing a blog post about your setup? It would be really helpful I think and I could link to it via the README?

**Comment by konradholub** [comment]
Unfortunately I don't own any blog
